# NOTICE: Generated By HttpRunner. DO'NOT EDIT!
# FROM: hogwarts-demo/testcases/login.yml
from httprunner import HttpRunner, TConfig, TStep


class TestCaseLogin(HttpRunner):
    config = TConfig(
        **{
            "name": "create a demo",
            "variables": {
                "login_email": "jeremy8250@gmail.com",
                "login_password": 592223,
            },
            "base_url": "https://www.processon.com/",
            "verify": False,
            "path": "hogwarts-demo/testcases/login_test.py",
        }
    )

    teststeps = [
        TStep(
            **{
                "name": "login",
                "variables": {},
                "request": {
                    "method": "POST",
                    "url": "/login",
                    "headers": {"Content-Type": "application/x-www-form-urlencoded"},
                    "data": {
                        "login_email": "$login_email",
                        "login_password": "$login_password",
                    },
                },
                "validate": [{"eq": ["status_code", 200]}],
            }
        ),
        TStep(
            **{
                "name": "create flow",
                "variables": {},
                "request": {
                    "method": "GET",
                    "url": "/diagraming/new",
                    "params": {"category": "flow"},
                },
                "extract": {"body": "body"},
                "validate": [{"eq": ["status_code", 200]}],
            }
        ),
        TStep(
            **{
                "name": "rename",
                "variables": {"chartId": "${get_chartId($body)}"},
                "request": {
                    "method": "POST",
                    "url": "/folder/rename/chart",
                    "headers": {"Content-Type": "application/x-www-form-urlencoded"},
                    "data": {
                        "title": "demo1234",
                        "ignore": "title",
                        "chartId": "$chartId",
                    },
                    "validate": [{"eq": "status_code"}, {"eq": 200}],
                },
            }
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
